
server:
  port: 9000

spring:
  application:
    name: jpa-project

  # DB 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_board?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    username: react
    password: Mysql1234!!
 
 
  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: create   
    # show-sql: true     # 콘솔에 출력
    properties:
      hibernate:       
        format_sql: true


# Logging
logging:
  level:
    root: INFO
    '[org.hibernate.SQL]': DEBUG             # SQL문 로그 출력
    '[org.hibernate.orm.jdbc.bind]': TRACE   # 중요 : 바인딩된 값 출력
